<?php

namespace AppBundle\Repository\Entity;

/**
 * AnimalPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalPostRepository extends \Doctrine\ORM\EntityRepository
{
}
